

POST http://localhost:3003/api/blogs
Content-Type: application/json

# {
#     "title": "Microservices and the First Law of Distributed Objects",
#     "author": "Martin Fowler",
#     "url": "https://martinfowler.com/articles/distributed-objects-microservices.html",
#     "userId": "609c07b0f1dcd81560840933"
# }

{
    "title": "Things I Don't Know as of 2018",
    "author": "Dan Abramov",
    "url": "https://overreacted.io/things-i-dont-know-as-of-2018",
    "userId": "609c0924f1dcd81560840935"
}